### ISSUE TITLE
TypeError: _urllib_post() got an unexpected keyword argument 'xapikey'

### ISSUE THREAD

**Issue by greensky92** [Adyen/adyen-python-api-library#72] opened 2019-07-23 03:58 UTC
**Python version**: 3.7.2
**Library version**: 2.0.0
**Description**

I followed the docs and ran into issue #66 .I tried adding the app_name workaround but I got this error instead.

```
Error: TypeError: _urllib_post() got an unexpected keyword argument 'xapikey'
    at PythonShell.parseError (/Users/Jibo/Documents/Experiments/stripe_client/node_modules/python-shell/index.js:246:21)
    at terminateIfNeeded (/Users/Jibo/Documents/Experiments/stripe_client/node_modules/python-shell/index.js:129:32)
    at ChildProcess.<anonymous> (/Users/Jibo/Documents/Experiments/stripe_client/node_modules/python-shell/index.js:121:13)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
    ----- Python Traceback -----
    File "/Users/Jibo/Documents/Experiments/stripe_client/python/adyen.py", line 57, in <module>
      get_list()
    File "/Users/Jibo/Documents/Experiments/stripe_client/python/adyen.py", line 25, in get_list
      'channel': 'Web',
    File "/usr/local/lib/python3.7/site-packages/Adyen/services.py", line 315, in payment_methods
      return self.client.call_checkout_api(request, action, **kwargs)
    File "/usr/local/lib/python3.7/site-packages/Adyen/client.py", line 448, in call_checkout_api
      **kwargs)
```

**Comment by danielWagnerr** [comment] 2019-08-07 14:20
I am also having this error, have you figured out how to fix it?

**Comment by danielWagnerr** [comment] 2019-08-07 17:20
I think I didn't find the real solution, but I just installed the requests package and it worked.

**Comment by Ishrock** [comment] 2019-08-09 11:00
the httpclient for urllib did not pass along the headers for the xapi key correctly.  I made some changes that where just merged to master that should fix the issue.  You can try pip installing the latest master if it isn't on pypi yet.

```bash
pip3 install git+ssh://git@github.com/Adyen/adyen-python-api-library#egg=Adyen
```

or

```
# requirements.txt
git+ssh://git@github.com/Adyen/adyen-python-api-library#egg=Adyen
```

**Comment by AlexandrosMor** [comment] 2019-08-09 11:06
Hello 
We made a release today 2.1.0. We included the @Ishrock PR. 
Let us know if the issue is fixed :)
Kind regards,
Alexandros

**Closed** 2020-05-07 07:43 UTC
